### ISSUE TITLE
What is the pointcloud.ply file released along with images and masks inside each sequence?

### ISSUE THREAD

**Issue by andrewsonga** [facebookresearch/cop3d#1]
Hello,

First of all, thank you for releasing this amazing dataset. I can only begin to imagine how much work it took to build this large-scale video dataset.

I wanted to ask the team a couple of questions regarding the composition of the dataset. Under each <sequence_name_x>, there exists directories "images", "masks", and "pointcloud.ply". The first two directories are self-explanatory, but I'm slightly confused as to what "pointcloud.ply" refers to.

- Is is the pointcloud outputted by running COLMAP on images with the foreground object masked out?
- Where are the camera poses located in all of this?

Thank you in advance :)

**Comment by shapovalov** [comment]
Hello Andrew and thanks for your kind words.

Point clouds are indeed obtained from COLMAP, which was run with the animals masked out, so they only contain the static part of the scene. They won‘t likely be of interest to most users.

Camera poses are stored in the metadata. See the tutorials here, they describe how to parse JSONs or SQLite to get, in particular, cameras: https://github.com/facebookresearch/cop3d/tree/main/examples

I hope this answers your questions. Feel free to reopen the issue otherwise.
